[build]
  command = "npm run build"
  functions = ".netlify/functions-internal"
  publish = "dist"

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/about-us.html"
  to = "/about-us/"
  status = 301

[[redirects]]
  from = "/contact.html"
  to = "/contact-us/"
  status = 301

[[redirects]]
  from = "/services/support-packages"
  to = "/services/wordpress-hosting-support"
  status = 301

[[redirects]]
  from = "/services/eco-hosting"
  to = "/services/wordpress-hosting-support"
  status = 301